name = "orbit-fund-management"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "fund-db"
database_id = "aa46ff75-26fc-4a0b-a3d0-9abdc08514c6"
